#!/bin/csh -x
#
# File:   qasm2pdf
# Date:   23-Mar-04
# Author: I. Chuang <ichuang@mit.edu>
#
# Shell script to convert qasm files to pdf, using the qasm2tex python script
#
# Usage:  qasm2pdf foo.qasm
#
# Produces: foo.pdf  (and also foo.tex, foo.epsf)

foreach i ($*)

        set d = `dirname $i`
        set b = `basename $i`
        set t = `echo $b | sed "s/.qasm//"`

	python2 qasm2tex.py $i >! $d/$t.tex
	if (-z $d/$t.tex) then
	    echo "error in qasm2tex on $t.tex! aborting."
	else
	    pdflatex -output-directory $d $d/$t.tex
	endif
end
