#!/bin/csh -x
#
# File:   qasm2png
# Date:   23-Mar-04
# Author: I. Chuang <ichuang@mit.edu>
#
# Shell script to convert qasm files to png, using the qasm2tex python script
#
# Usage:  qasm2png foo.qasm
#
# Produces: foo.png  (and also foo.tex, foo.epsf)

set GS = "gs -sDEVICE=pnmraw -r400 -dNOPAUSE"

foreach i ($*)

        set d = `dirname $i`
        set b = `basename $i`
        set t = `echo $b | sed "s/.qasm//"`

	python2 qasm2tex.py $i >! $d/$t.tex
	if (-z $d/$t.tex) then
	    echo "error in qasm2tex on $t.tex! aborting."
	else
	    #pdflatex -output-directory $d $d/$t.tex
	    latex2png $d/$t.tex
	endif
end
